name: Scaffold repo structure
on:
  workflow_dispatch: {} # Manual trigger only - run when needed to set up directory structure
permissions:
  contents: write
jobs:
  scaffold:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create directories & files
        shell: bash
        run: |
          set -euo pipefail
          # write the stdin payload to $1 if the file does not exist
          write_if_missing () {
            local path="$1"
            if [ ! -f "$path" ]; then
              mkdir -p "$(dirname "$path")"
              # read here-doc from stdin and write to file
              cat > "$path"
            fi
          }
          # touch .gitkeep in an empty dir to ensure it persists in git
          keep () {
            mkdir -p "$1"
            : > "$1/.gitkeep"
          }
          
          ############ ROOT FILES ############
          write_if_missing "README.md" <<'EOF'
# OWISAC PRISMA Review - Replace this placeholder with actual project description
EOF
          write_if_missing "LICENSE" <<'EOF'
Replace this placeholder with the actual license text (MIT/CC-BY etc.).
EOF
          write_if_missing "supplementary_material.md" <<'EOF'
# Supplementary Material
Replace this placeholder with descriptions of supplementary figures/tables.
EOF
          
          ############ data/ directory with .gitkeep ############
          # Ensure data directory persists even if empty
          keep "data"
          write_if_missing "data/included_studies.csv" <<'EOF'
record_id,doi_or_id,venue,year,title,authors,SRC,TRACE,architecture,channel_regime,wavelength_nm,primary_outcome,task_domain,data_availability,opa_N_elements,opa_pitch_um,opa_phase_bits,opa_scan_range_deg,opa_scan_rate_hz,ris_size_elems,ris_lattice,ris_phase_states,ris_response_ms,ris_fill_factor,z_total_m,nlos_geometry,Cn2,r0_m,rytov_var,regime,pillar_WD_JD,pillar_RC_PR_T,pillar_BN_RIS,pillar_RPB_Kol,pillar_HW_Q_CTRL,optimizer,training_signal,snr_db,sinr_db,ber,evm_pct,psl_db,islr_db,hpbw_deg,contrast,roc_auc,crb_unit,runtime_s,mem_gb,baselines_present,realism_score,rob_overall,normalization_notes,notes
# Replace this header-only CSV with actual study data
EOF
          write_if_missing "data/excluded_studies.csv" <<'EOF'
record_id,doi_or_id,year,title,authors,reason
# Replace this header-only CSV with actual excluded studies data
EOF
          write_if_missing "data/screening_log.csv" <<'EOF'
date,source,query_id,hits,included_phase1,included_phase2,notes
# Replace this header-only CSV with actual screening log data
EOF
          
          ############ protocol/ directory with .gitkeep ############
          # Ensure protocol directory persists even if empty
          keep "protocol"
          write_if_missing "protocol/prisma_protocol.md" <<'EOF'
# PRISMA-P Protocol
Replace this placeholder with OSF/PROSPERO registration details and protocol content.
EOF
          write_if_missing "protocol/search_strategy.md" <<'EOF'
# Search Strategy
Replace this placeholder with database queries, dates, and search snapshots.
EOF
          # Create instruction file for binary placeholders instead of fake binary files
          write_if_missing "protocol/README_PLACEHOLDERS.txt" <<'EOF'
# Protocol File Placeholders

This directory requires the following files to be manually uploaded:

1. prisma_checklist.pdf - Replace this placeholder instruction with the actual PRISMA checklist PDF
2. data_extraction_form.xlsx - Replace this placeholder instruction with the actual Excel data extraction form

Please upload these files manually after running this scaffold workflow.
EOF
